services:

  model:
    provider:
      type: model
      options:
        model: ai/gemma3:4B-F16

  client:
    build:
      context: .
      target: client-dev
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./client
          action: sync
          target: /usr/local/app
        - path: ./client/package-lock.json
          action: rebuild

  api:
    build:
      context: .
      target: api-dev
    ports:
      - 3000:3000
    environment:
      OPENAI_BASE_URL: http://model-runner.docker.internal/engines/v1
      OPENAI_MODEL: ai/gemma3:4B-F16
    volumes:
      - game-state:/etc/game-state
    develop:
      watch:
        - path: ./api
          action: sync
          target: /usr/local/app
        - path: ./api/package-lock.json
          action: rebuild


volumes:
  game-state: