services:
  app:
    image: michaelirwin244/ai-game
    ports:
      - 3000:3000
    models:
      gemma3:
        endpoint_var: OPENAI_BASE_URL
        model_var: OPENAI_MODEL

volumes:
  game-state:

models:
  gemma3:
    model: ai/gemma3:4B-F16