services:
  client:
    build:
      context: .
      target: client-dev
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./client
          action: sync
          target: /usr/local/app
        - path: ./client/package-lock.json
          action: rebuild

  api:
    build:
      context: .
      target: api-dev
    ports:
      - 3000:3000
    models:
      gemma3:
        endpoint_var: OPENAI_BASE_URL
        model_var: OPENAI_MODEL
    volumes:
      - game-state:/data
    develop:
      watch:
        - path: ./api
          action: sync
          target: /usr/local/app
        - path: ./api/package-lock.json
          action: rebuild


volumes:
  game-state:

models:
  gemma3:
    model: ai/gemma3:4B-F16